# Site Settings

title: Race Radar
description: Discover your next race
email: info@race-radar.com

# Build settings

markdown: kramdown
permalink: pretty

port: 4000


sass:
  sass_dir: assets/css
  style: :nested